export const tooltipMessage = {
    'signup': 'Sign Up',
    'login': 'Login',
    'language': 'language',
    'english': 'English',
    'arabic': 'Arabic',
    'spanish': 'spanish',
    'post_job': 'Post a Job',
    'my_profile': 'Profile',
    'my_employee_profile': 'My Employee Profile',
    'my_employer_profile': 'My Employer Profile',
    'my_bookings': 'My Bookings',
    'my_messages': ' My Messages',
    'my_order': ' My Order',
    'my_jobs': 'My Jobs',
    'my_posted_jobs': 'My Posted Jobs',
    'running_jobs_client': 'My Running Jobs (as Client)',
    'running_jobs_freelancer': 'My Running Jobs (as Freelancer)',
    'my_applied_jobs': ' My Applied Jobs',
    'all_jobs': 'All Jobs',
    'my_shop': 'My Shop',
    'my_services': 'My Services',
    'shop_gallery': 'Shop Gallery',
    'wallet': 'Wallet',
    'logout': 'Logout',
    'home': 'Home',
    'search_employee': 'Search for an employee',
    'search_job': 'Search for a job',

    /*create job*/
    'templete': 'Template',
    'templete_text': 'Would you like to use a template?',
    'templete_button1': 'Use a Template',
    'templete_button2': 'Start a New Job',

    /*subscrtion messages*/
    'successful_subscribe': 'Subscribed Successfully!',
    'error_subscribe': 'Email Already Subscribed!',
    'msg_subscribe': 'You Are Subscribed Successfully',
    'successful_unsubscribe': 'Unsubscribed Successfuly!',
    'error_unsubscribe': 'You Are Not Subscribed!',

    /*withdrawal message*/
    'withdrawl_success_msg': 'You have successfully requested the withdrawal.',
    'withdrawl_error_msg': 'You can\'t withdraw more than the amount on your balance',
    'withdrawl_error_min_amount': 'The minimum withdrawal amount is ',
    'admin_withdraw_subject': 'Withdrawal Request Approved',
    'user_withdraw_subject': 'Payment Withdrawal Request',

    /*delete account message*/
    'delete_fill_msg': 'Enter code as received in your Email',
    'delete_error_msg': 'Account Closure not successful. Please try again',
    'enter_email': 'Please enter email and/or password',
    'some_error': 'Account closure not successful. Please try again',
    'account_ver': 'Account closure verification',
    'invalid_credential': 'Invalid credentials',

    /*payment process*/
    'add_payment': 'Make an Additional Payment for',
    'job_promote_payment': 'Make a Payment for',
    'job_payment': 'Make Payment for',
    'promotion': 'promotion',
    'job_promote_promotion': 'job boosting',
    'category_promote_promotion': 'category boosting',
    'pay_with_card': 'Pay with card',
    'pay_to_escrow_account': 'Pay to Escrow Account',
    'verify_card': 'Verify Card',
    'money_is_payed_to_escrow': 'The amount will be transferred to the Escrow Account and will be released by you when the employee finishes the job.',

    /*new design header*/
    'about_us': 'About Us',
    'how_it_works': 'How It Works',
    'faq_header': 'FAQ',
    'signin': 'Sign In',
    'categories': 'Categories',
    'choose_the_categories': 'Choose the Categories',
    'choosen_categories': 'Chosen Categories:',
    'save': 'Save',
    'search_for_a_job': 'Search for a job',
    'on_map': 'On Map',
    'find': 'Find',
    'recieved_offers': 'Received Offers',
    'success_recieved_offer': 'You successfully applied for the job. The job is moved to My Biddings',
    'sent_proposal': 'My Biddings',
    'current_job_as_freelancer': 'Current Jobs As Freelancer',
    'current_job_as_client': 'Current Jobs As Client',
    'current_job': 'Current Jobs',
    'closed_jobs': 'Completed  Jobs',
    'recent_jobs': 'Recent Jobs',
    'best_matches': 'Best Matches',
    'job_categories': 'Categories',
    'favourite_jobs': 'Favourite Jobs',
    'hidden_jobs': 'Hidden Jobs',
    'notifications': 'Notifications',
    'switch_to': 'Switch to',
    'create_service_post': 'Create service post',
    'create_job_post': 'Create job post',
    'personal_information': 'Personal Information',
    'edit_profile': 'Edit profile',
    'my_profile': 'Profile',
    'private_chat': 'Private Chat',
    'general_setting': 'Settings',
    'toggle_navigation': 'Toggle navigation',
    'password_not_match': 'Password does not match',
    'put_password': 'Enter the password to continue',
    'intro_text': 'Make sure to contact the Employer via chat to arrange the details',
    'intro_text1': 'Make sure to contact the employee via chat to arrange the details',
    'my_contracts': 'My Contracts',
    'sent_offers': 'Sent Offers',
    'no_sent_offers': 'You haven’t sent any offers yet',
    'recieved_proposals': 'Received Application',
    'no_recieved_offers': 'You haven’t recieved any offers yet',
    'no_hidden_offers': 'You don’t have hidden offers',
    'current_contracts': 'Current Contracts',
    'closed_contracts': 'Closed Contracts',
    'favourite_employees': 'Favourite Employees',
    'hidden_employees': 'Hidden Employees',
    'use_my_location': 'Use my location',

    /*confirmation text*/
    'confirmation_text': 'Welcome to Djobzy! You are all set. Now you can',
    'confirmation_login': 'Log in',

    /*Hire Process*/
    'hire_title': 'Send a Job Offer',
    'hire_about': 'About The Employee',
    'hire_button': 'Send An Offer',
    'offer_sent_success': 'Your offer has been sent successfully',

    /*419*/
    'error_title': 'Your Session has expired',

    /*index*/
    'convenient_affordable_around_home': 'The convenient & affordable way to get things done around the home',
    'taskers_help_without_breaking_bank': 'Choose from over 140,000 vetted Taskers for help without breaking the bank.',
    'need_something_different': 'Need something different?',
    'get_started': 'Get Started',
    'how_works': 'How it works',
    'describe_task': 'Describe the task',
    'describe_task_para1': 'Choose from a variety of home services and select the day and time you\'d like a qualified Tasker to show up. Give us the details and we\'ll find you the help.',
    'get_matched': 'Get matched',
    'get_matched_para1': 'Select from a list of qualified and fully vetted Taskers for the job. Choose Taskers by their hourly rate and start chatting with them right in the app.',
    'get_done': 'Get it done',
    'get_done_para1': 'Just like that, your Tasker arrives and gets the job done. When your task is complete, payment will happen seamlessly and securely through the app.',
    'customers_get_millions': 'Customers use to get millions of projects done',
    'quickly_easily': 'quickly and easily',
    'get_more_anytime_anywhere': 'Get more done anytime, anywhere',
    'get_more_anytime_anywhere_para1': 'Send project requests, get quotes, and hire the right pro with the free Thumbtack app for iPhone.',
    'thousands_professionals_growing': 'Thousands of professionals are growing their',
    'businesses': 'businesses',
    'designer': 'Designer',
    'developer': 'Developer',
    'analyst': 'Analyst',
    'choose_text': 'Choose from vetted Taskers for help without breaking the bank',
    'choose_text1': 'Djobzy is a Creative Way for <strong>Individuals & Companies</strong> to',
    'choose_text2': '<strong>Employ & Get Employed</strong> with Guaranteed Work On their <strong>Own Schedule</strong>',
    'buttom_text1': 'I am looking for someone, to take care of my dog for a day',
    'buttom_text2': "A singer is needed for my  wedding in two weeks",
    'buttom_text3': "I'm looking for an electrician for my parent's house in Vancouver",
    'buttom_text4': 'Family farm needs a temporary worker for some gardening works',
    'buttom_text5': 'A lawyer is neeed in berlin top help with some visa problems',
    'buttom_text6': 'We need a truck diver to take our staff to our new house in London',
    'buttom_text7': 'I need someone to get my parcel from airport and deliver it to my office',

    /*new design index*/
    'watch_video': 'Watch Video',
    'find': 'Find',
    'the': 'the',
    'best': 'Best',
    'find_the_best_content': 'Choose from over 140,000 vetted Taskers for help without breaking the bank.',
    'search_for_a_employee': 'Search for an employee',
    'scroll': 'Scroll',
    'get_work_done': 'Get Work Done!',
    'take_a_job': 'Take a Job!',
    'keep_in_touch': 'Keep in Touch!',
    'start_now': 'Start Now',
    'start_now_content': 'It only takes 15 seconds',
    'view_more_categories': 'View more categories',
    'top_jobs': 'Top Jobs',
    'view_more_jobs': 'View more jobs',
    'min_ago': 'min. ago',
    'hour_ago': 'hour ago',
    'i_need_a': 'I need a',
    'start_now_content2': 'Start Now! It only takes 15 seconds',
    'learn_more': 'Learn More',
    'see_all': 'See All',

    /*register*/
    'register': 'Register',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'phone_no': 'Phone No',
    'male': 'Male',
    'female': 'Female',
    'user_type': 'User Type',
    'customer': 'Customer',
    'seller': 'Seller',
    'create_account': 'Create an Account',
    'already_have_account': 'Already have an account?',
    'sign_in': 'Sign in',
    'email_comfirmation': 'Email Confirmation for Registration',
    'email_success_msg': 'We sent you an registration imformation mail. Please check your registered email.',

    /*login*/
    'remember_me': 'Remember Me',
    'forgot_your_password': 'Forgot Your Password?',
    'not_registered': 'Not Registered?',
    'create_an_account': 'Create an account',

    /*forgot password*/
    'reset_password': 'Reset Password',
    'enter_email_instructions_reset_password': 'Enter your email and we\'ll send you instructions to reset your password',
    'send_password_reset_link': 'Send Password Reset Link',

    /*dashboard*/
    'dashboard': 'My Dashboard',
    'user_type': 'User Type :',
    'account_settings': 'Account Settings',
    'log_out': 'Log Out',
    'username': 'Username',
    'email_address': 'Email Address',
    'gender': 'Gender',
    'photo': 'Photo',
    'update': 'Update',
    'upload_photo': 'Upload Photo',
    'hourly_price': 'Hourly Price',

    /*new design dashboard*/
    'dashboard_hello': 'Hello',
    'welcome': 'Welcome to Djobzy',
    'welcome_content': 'Improve your Profile',
    'loggedin': 'You are logged in as an',
    'employee': 'Employee',
    'active': 'Active',
    'jobs': 'Jobs',
    'verification': 'Verification',
    'personal_info_text1': 'Verification level 2 is mandatory to fully unlock Djobzy’s features.',
    'personal_info_text': ' We strongly suggest to continue verifying your account to the highest verification level. The higher you verify, the more chance of gaining mutual trust and landing a job or finding a proper employee.',
    'level': 'Level',
    'new': 'New',
    'messages': 'Messages',
    'rating': 'Rating',
    'payments': 'Payments',
    'my_wallet': 'Wallet',
    'switch': 'Switch',
    'your_verification_level': 'Your Verification Level',
    'verification_content': 'Higher Verification levels increase your chances of landing a job or finding employees, Would show you higher in search results, Enable you to gain others trust more easily and enhance your Djobzy Experience.',
    'phone': 'Phone',
    'number': 'Number',
    'social_media': 'Social Media',
    'account': 'Accounts',
    'id_card': 'ID Card &',
    'certification': 'Certificates',
    'credit_debit': 'Credit / Debit',
    'card': 'Card',
    'verification': 'Verification',
    'interview': 'Interview &',
    'background': 'Background',
    'check': 'Check',
    'find_jobs': 'Find Jobs',
    'advance_serach': 'Advanced Search',
    'location': 'Location',
    'km': 'km',
    'clear_all': 'Clear All',
    'apply': 'Apply',
    'my_provided_service': 'My Promoted Services',
    //'provided_service' : 'Job Requests',
    'provided_service': 'Promoted Services',
    'create_new_provided_service': 'Promote your services',
    'create_new_provided_service_header': 'Promote Services',
    'hotel_room_tooltip': 'Manage your hotel’s rooms, pricing, and availability.',
    'hotel_refund_policy': 'Your refund will be processed within 3-5 business days after cancellation. The amount will be credited to your original payment source.',
    'more': 'More',
    'more_categories': 'More categories',
    'promote': 'Boost',
    'suggested_jobs_by_categories': 'Suggested Jobs by Categories',
    'suggested_jobs': 'Suggested Jobs',
    'sort_by': 'Sort By',
    'all': 'All',
    'distance': 'Distance',
    'date_added': 'Date added',
    'sort_order': 'Sort Order',
    'ascending': 'Ascending',
    'descending': 'Descending',
    'hour_rate': 'Hourly Rate:',
    'hour': 'Hourly',
    'hour_rates': 'Hourly Rate',
    'fixed_rate': 'Total Price:',
    'fixed_rates': 'Total Price',
    'fixed': 'Total',
    'total_hours': 'Total Hour',
    'total_earn': 'Total Earn',
    'total': 'Total',
    'expected_time': 'Expected Hours:',
    'expected_times': 'Expected Hours',
    'expected': 'Expected',
    'expected_note': 'is expected for the job to be done.',
    'time': 'Hours',
    'hours': 'Hours',
    'about_me': 'About Me',
    'more': 'More',
    'na': 'N/A',
    'view_profile': 'View Profile',
    'verification_level': 'Verification Level:',
    'usd': 'USD',
    'five': '5',
    'seven': '7',
    'zero': '0',
    'view': 'View',
    'no_data_found': 'No Data Found',
    'radius': 'Radius',
    'service_packs': 'Promoted Services',
    'service': 'Service',
    'packs': 'Packs',
    'emp_offer': "Employer's offered price",
    'offer_price': 'Offered price',

    /*Profile Page*/
    'copy_link': 'Copy Link',

    /*employer dashboard*/
    'employer': 'Employer',
    'start_today': 'What whould you start today?',
    'start_today_content1': 'It takes from around',
    'start_today_content2': '2 minutes',
    'start_today_content3': 'to post a new job and the future employee can start performing immediately',
    'start_a_new_job': 'Post a New Job',
    'my_job_posts': 'Job Posts',
    'proposals': 'Biddings:',
    'you_dont_have_active_job_post': 'You don’t have an active job post',
    'you_dont_have_active_contract': 'You don’t have an active contract',
    'create_job_post': 'Create Job Post',
    'create_service_post': 'Create service Post',
    'active_contracts': 'Active Contracts',
    'money_spent1': 'Money Spent:',
    'start': 'Start:',
    'deadline': 'Deadline:',
    'suggested_profile': 'Suggested Profiles',
    'prepare_meal_deliver': 'I will prepare meal and deliver it to your house',
    'no_profile_found': 'No Profile Found...',

    /*new design faq*/
    'all_questions': 'All Questions',
    'registration': 'Registration',
    'for_employers': 'For Employers',
    'for_employees': 'For Employees',
    'general_questions': 'General Questions',
    'archive': 'Archive',

    /*new design result*/
    'find_employees': 'Find Employees',
    'keyword': 'Keyword',
    'add_a_category': 'Add a category',

    /*create job*/
    'title_and_description': 'Title and Description',
    'description': 'Description',
    'title': 'Title',
    'choose_category': 'Choose Category',
    'category': 'Category',
    'categorys': 'Categories',

    /*job details*/
    'total': 'Total',
    'contracts': 'Contracts',
    'money': 'Money',
    'spent': 'Spent',
    'about_the_employer': 'About the employer',
    'see': 'See',
    'other_jobs': 'other jobs',
    'fixed_price': 'Total Price',
    'project_length': 'Project Length',
    'hourly_rate': 'Hourly Rate',
    'requirements': 'Requirements',
    'posted': 'posted',
    'ago': 'ago',
    'conversational': 'Conversational',
    'description': 'Description',
    'similar_jobs': 'Similar Jobs',
    'address_of_the_job': 'Address of the job',
    'applied': 'Applied',
    'see_payments': 'Payment Details',
    'payment_for': 'Payment For',
    'report_issue_dispuit': 'Report an Issue/Dispute',
    'initiate_a_dispute': 'Initiate a Dispute',
    'withdraw_money': 'Withdraw Money',
    'chat': 'Chat',
    'completed': 'Completed',
    'see_my_offer': 'See My Offer',
    'bidding_job': 'Candidate is bidding for this job',
    'bidding_jobs': 'Candidates are bidding for this job',
    'no_bidding_job': 'No Biddings Yet',
    'change_my_offer': 'Change My Offer',
    'my_offer': 'My Offer',
    'my_new_offer': 'My New Offer',
    'previous_bids': 'Previous bids',
    'bidding_profiles': 'Bidding Profiles',
    'job_title': 'Job Title',
    'previous_bid_price': 'Previous Bid Price',
    'new_bid_price': 'New Bid Price',
    'send': 'Send',
    'view_profile': 'View Profile',
    'bid_amount': 'Bid Amount',
    'report_as_inappropriate': 'Report as Inappropriate',
    'request_to_end_this_job': 'Request to end this job',
    'first_bid': 'Apply First',
    'bid_amount': 'Bid Amount',
    'apply_for_the_job': 'Apply for the Job',
    'requested_price': 'Requested price',
    'offer_price': 'Offer price',
    'per_hour': 'per hour',
    'offer_your_price': 'Offer your price',
    'introduction_letter': 'Introduction Letter',
    'are_you_report': 'Are you sure you want to report an issue and start a Dispute?',
    'are_you_report_employee': 'Are you sure you want to report this employee?',
    'change_bid_success': 'Your offer has been changed successfully',
    'change_bid_error': 'Due to some reason, your offer has not been changed, please try after sometime',
    'bid_apply_success': 'You applied for this job',
    'bid_apply_error': 'Due to some reason, your application not submitted properly, please try after sometime',

    /*employer job details*/
    'bidding_profiles': 'Bidding Profiles',
    'hire': 'Hire',
    'hired': 'Hired',
    'chat': 'Chat',
    'view_my_job_post': 'View My Job Post',
    'view_my_job_posts': 'View Full Job Post',
    'mores': 'more...',
    'bid': 'Bid',
    'yes': 'Yes',
    'no': 'No',
    'are_you_hire': 'Are you sure you want to hire this employee?',
    'pay_hire': 'Pay And Hire This Employee',
    'pay_escrow': 'Pay to Escrow Account',
    'pay_extra': 'Pay to Extra Payment',
    'intro_text2': 'Make sure to contact the employee via chat to arrange the details.',
    /*current job details*/
    'hourly': 'Hourly',
    'rate': 'Rate',
    'project': 'Project',
    'length': 'Length',
    'new': 'New',
    'messages': 'Messages',
    'start_date': 'Start Date',
    'contract_id': 'Contract ID',
    'current_jobs': 'Current Jobs',
    'end_this_job': 'End this Job',
    'end_this_jobs': 'Please confirm that you want to end this Job',
    'request_to_end': 'Are you sure you want to request for end this job?',
    'end_this': 'Are you sure you want to end this?',
    'req_succ_msg': 'You have successfully requested to End this Job',
    'end_succ_msg': 'You have successfully End this Job',
    'req_err_msg': 'You have not successfully requested to End this Job',
    'end_err_msg': 'You have not successfully End this Job',
    'code_sent': 'Code sent in your email',
    'total_hour_val': 'Hourly rate should be equal or less than fixed rate',
    'back_to': 'Back to the job',
    'my_active_job': 'My active job',
    'active_job': 'Active job',

    /*my booking*/

    'no_booking_found': 'No booking found!',
    'booking_id': 'Booking Id',
    'payment_method': 'Payment Method :',
    'leave_review': 'Leave a Review',
    'release_payment': 'Release the payment',
    'dispute': 'Dispute',
    'subject': 'Subject :',
    'message': 'Message:',
    'submit': 'Submit',
    'close': 'Close',
    'invoice': 'Invoice',
    'cancel_booking': 'Cancel this booking',
    'total_price': 'Total Price -',
    'payment_status': 'Payment Status',
    'cancel': 'Cancel',
    'save': 'Save',
    'service_status': 'Service Status :',
    'awaiting_completion': 'Awaiting completion',
    'completed': 'Completed',
    'released_payment': 'Released the payment',
    'dispute_status': 'Dispute Status :',
    'pending_withdrawal': 'Pending Withdrawal',
    'awaiting_admin_action': 'Awaiting for admin action',
    'enter_your_review_here': 'Enter your review here...',
    'pending_payments': 'Pending Payments',
    'received_payments': 'Received Payments',
    'escrow_account': 'Escrow Account',
    'my_released_payments': 'My Released Payments',
    'withdrawal_details': 'Withdrawal Details',
    'payPal_ID': 'PayPal ID',
    'first_name': 'First Name',
    'surname': 'Surname',
    'card_issuing_country': 'Card Issuing Country',
    'card_number': 'Card Number',
    'expiry_date': 'Expiry Date',
    'card_expiry_date': 'Card Expiry Date',
    'full_beneficiary_name': 'Full Beneficiary Name',
    'beneficiary_address': 'Beneficiary Address',
    'bank_name': 'Bank Name',
    'bank_address': 'Bank Address',
    'swift_code': 'SWIFT Code/BIC Code',
    'iban_account_number': 'IBAN/Account Number',
    'sort_code': 'Sort Code',
    'transit_number': 'Transit Number',
    'institution_number': 'Institution Number',

    /*vendor*/
    'send_message': 'Send Message',
    'services': 'Services',
    'profile': 'Profile',
    'reviews': 'Reviews',
    'gallery': 'Gallery',
    'contact_vendor': 'Contact Vendor',
    'book_now': 'Book Now',

    /*profile*/
    'description': 'Description',
    'contact_address': ' Contact Address',
    'shop_working_days': 'Shop Working Days',
    'sunday': 'Sunday',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',

    /*new design profile*/
    'see_on_map': 'See On Map',
    'number_of_jobs': 'Number of jobs',
    'money_earned': 'Money Earned',
    'money_spent': 'Money Spent',
    'languages': 'Languages',
    'education': 'Education',
    'assets': 'Assets and software programs',
    'vehicle': 'Vehicle',
    'my_involed_category': 'My Involved Categories',
    'involed_category': 'Involved Categories',
    'view_promotion': 'View Promotions',
    'boosted_categories': 'Boosted Categories',
    'boost': 'Boost',
    'boosted_jobs': 'Boosted Job Posts',
    'view_boosted_jobs': 'View Boosted Jobs',
    'add_category': 'Add Category',
    'create_new': 'Create New',
    'job_request': 'Job Request',
    'profile_link': 'Profile link',
    'share': 'Share',
    'download_profile': 'Download Profile',
    'licenses': 'Licenses',
    'certificates': 'Certificates',
    'edit': 'Edit',
    'attachments': 'Attachments',
    'personal_video': 'Personal Videos',
    'add': 'Add',
    'attachment': 'Attachment',
    'no_data_found': 'No data found...',
    'view_employer_profile': 'View Employer Profile',
    'view_employee_profile': 'View Employee Profile',

    /*review*/
    'no_reviews': ' No Reviews',
    'review_text': 'Are you sure you want to submit this review?',

    /*admin review*/
    'review_success_msg': 'Review deleted successfully',
    'review_error_msg': 'Review not deleted successfully',

    /*admin chat*/
    'chat_success_msg': 'Chat deleted successfully',
    'chat_error_msg': 'Chat not deleted successfully',

    /*contact vendor*/
    'your_name': 'Your Name',
    'your_email': 'Your Email',
    'your_phone_no': 'Your Phone No',
    'your_message': 'Your Message',

    /*send message*/
    'to': 'To :',
    'your_message': 'Your Message :',
    'send': 'Send',

    /*booking*/
    'cover_banner': 'cover banner',
    'profile_hoto': 'Profile Photo',
    'choose_service': 'Choose A Service',
    'select_date': 'Select Date',

    'address': 'Address',
    'select_time': 'Select Time',
    'none': 'None',
    'city': 'City',
    'payment_mode': 'Payment Method',
    'pincode': 'Pin Code',
    'note': 'Note',
    'create_new_account': 'Create New Account',
    'email': 'Email',

    /*shop search*/
    'search': 'Search',
    'filter': 'Filter',
    'view_shop_book': 'View Shop & Book',
    'no_shop_found': 'No shop found!',
    'enter_city': 'Enter City',
    'star_rating': 'Star Rating',
    'one_star': '1 Star',
    'two_stars': '2 Stars',
    'three_stars': '3 Stars',
    'four_stars': '4 Stars',
    'five_stars': '5 Stars',
    'view_profile_book': 'View Profile & Book',

    /*messages*/
    'sno': 'Sno',

    /*My Orders*/
    'my_orders': 'My Orders',
    'no_order_found': 'No order found!',
    'order_id': 'Order Id',
    'services_name': 'Services Name',
    'booking_date': 'Booking Date',
    'booking_time': 'Booking time',
    'booking_note': 'Booking Note',
    'user_email': 'User Email',
    'total_amount': 'Total Amount',
    'status': 'Status',
    'reject': 'Reject',
    'service_complete': 'Service Complete?',
    'mark_complete': 'Mark as complete',
    'customize_budget': 'Customize budget',
    'minimum_budget': ' Minimum Budget',
    'maximum_budget': 'Maximum Budget',
    'estimate_delivery': 'Estimate Delivery',
    'days': 'days',
    'estimate_delivery_days': 'Estimate Delivery days',
    'preferred_location': 'Preferred location',
    'mandatory_fields': '- is mandatory fields',

    /*new request*/
    'whoops': 'Whoops!',
    'some_problems_with_your_input': 'There were some problems with your input.',
    'choose_name_your_project': 'Choose a name for your project',
    'tell_us_more_about_your_project': 'Tell us more about your project',
    'category': 'Category',
    'select': 'Select',
    'select_category': 'Select Category',
    'sub_category': 'Sub Category',
    'upload_files': 'Upload Files',
    'please_upload_only': '(Please upload only : JPG,JPEG,PNG,GIF,PDF,DOC,DOCX)',
    'featured_image': 'Featured Image',
    'what_skills_required': 'What skills are required?',
    'what_your_estimated_budget': 'What is your estimated budget?',
    'micro_project': 'Micro Project',
    'simple_project': 'Simple project',
    'very_small_project': ' Very small project',
    'small_project': 'Small project',
    'medium_project': 'Medium project',
    'large_project': 'Large project',
    'very_large_project': 'Very Large project',
    'huge_project': 'Huge project',
    'major_project': 'Major project',
    'basic': 'Basic',
    'moderate': 'Moderate',
    'standard': 'Standard',
    'skilled': 'Skilled',
    'expert ': 'Expert',

    /*My request*/
    'my_posted_job': 'My Posted Job',
    'date': 'DATE',
    'job_name': 'JOB NAME',
    'delivery': 'DELIVERY',
    'estimated': 'ESTIMATED',
    'action': 'ACTION',
    'feature_job_c': 'FEATURE JOB?',
    'message_freelancer': 'MESSAGE TO FREELANCER',
    'fund_status': 'FUND STATUS',
    'bids': 'Bids',
    'delete': 'Delete',
    'featured_progress': 'FEATURED - progress',
    'featured_c': 'FEATURED',
    'make_feature': 'Make it feature',
    'not_available': ' Not Available',
    'fund_now': 'Fund Now',

    /*chat*/
    'conversation_with': 'Conversation With',
    'send_a_message': 'Send a Message',
    'back': 'Back',

    /*buyer track*/
    'track_job': 'Track Job',
    'chat_with': 'Chat with',
    'payment_accpted': 'PAYMENT ACCEPTED',
    'payment_accpted_para1': 'Your payment for this order was successfully collected by us. Seller will be paid when the order is complete.',
    'seller_started_submit_information': 'THE SELLER WILL ONLY GET STARTED AFTER YOU SUBMIT THIS INFORMATION',
    'requires_information_order_get_started': 'requires the following information in order to get started',
    'you_purchased_extras': 'You also purchased the following extras:',
    'you_purchased_following': 'You also purchased the following:',
    'shipping_rate': 'Shipping Rate :',
    'your_order_sent_to_seller': 'YOUR ORDER WAS SENT TO THE SELLER',
    'thank_you_order_sent_seller': ' Thank You. Your order was sent to the Seller',
    'expected_delivery': 'Expected delivery:',
    'seller_suggested_mutual_cancellation': 'Seller suggested a mutual cancellation ',
    'mutual_cancellation': 'YOU SUGGESTED A MUTUAL CANCELLATION.',
    'your_order_ready': 'Your order is ready!',
    'rejected_seller_work': 'You rejected the the seller\'s work',
    'withdrawn_mutual_cancellation': 'You withdraw the mutual cancellation suggestion.',
    'seller_withdrawn_mutual_cancellation_proposal': 'The seller has withdrawn the mutual cancellation proposal.',
    'abort_cancellation_continue': 'Abort cancellation and continue with this order.',
    'order_cancelled_automatically_unless_rejected_aborted': 'This order will be cancelled automatically in two days unless it is rejected or aborted.',
    'reject_cancellation': 'Reject Cancellation',
    'accept_cancellation': 'Accept Cancellation',
    'please_rate_review_experience': 'Please rate & review your experience',
    'order_cancelled': 'The order was cancelled',
    'order_cancelled_mutual_agreement_funds_returned': 'The order was cancelled by mutual agreement. Funds were returned to you.',
    'file_attachment': 'Add a file attachment',
    'accepted_file_formats': 'Accepted File Formats: jpeg, jpg, gif, png, tif, bmp, avi, mpeg, mpg, mov, rm, 3gp, flv, mp4, zip, rar, mp3, wav, wma and ogg',
    'got_problem': 'Got Problem?',
    'no': 'No',
    'yes': 'Yes',
    'reject_delivered_work': 'Reject Delivered Work',
    'seller_redeliver_available_after_delivery.': 'The seller will have to redeliver the work. Available only after order delivery.',
    'seller_agree_cancel': 'You and the Seller Agree to Cancel',
    'order_late_cancel': 'Your order is about to be late. You will be able to cancel it in this and that time.',
    'out_ideas': 'Out of Ideas?',
    'tips_solutions_order': ' Tips and solutions for common order problems.',
    'faq': 'Some frequently asked questions to help you',
    'seller_not_respond_messages': 'Seller does not respond to my messages',
    'seller_not_respond_messages_para1': 'Some sellers take more time then others to respond: Time difference, local holidays and personal constraints are typical reasons for lack of response. If you feel the seller is taking too long you can initiate a Mutual Cancellation Request.',
    'delivered_advertised_seller': 'Delivered work was not as advertised by the seller',
    'delivered_advertised_seller_para1': 'You have three days to reject the submitted work. If you choose to reject, make sure you specify your issues with that order clearly. To reject the seller\'s work simply choose Reject the Work.',
    'order_completed': 'Order Completed!',
    'this_order_complete': 'This order is complete. You can ',
    'talking_seller': 'continue talking with the seller in the conversation page.',
    /*new*/
    'ordered_from': 'Ordered from',
    'reason': 'Reason',
    'add_feedback_this_shown_public': 'Please add your feedback. This will be shown to the wide public so other users can benefit from your experience.',

    /*seller track*/
    'ordered_by': 'Ordered by',
    'new_order_created': 'New order created',
    'need_deliver_work_deadline_get_paid': 'You need to deliver your work before your deadline to get paid.',
    'deadline': 'Deadline',
    'order_requirements_submitted': 'Order Requirements Submitted',
    'buyer_responded_instructions': 'The buyer responded to your instructions.',
    'order_purchased_extras': 'This order purchased the following extras:',
    'order_purchased': 'This order purchased the following:',
    'buyer_suggested_mutual_cancellation': 'Buyer suggested a mutual cancellation',
    'buyer_Withdrawn_cancellation_proposal': 'The buyer has withdrawn the mutual cancellation proposal.',
    'withdrawn_mutual_cancellation_suggestion': 'You withdrawn the mutual cancellation suggestion.',
    'order_cancelled__Funds_returned_buyer': 'The order was cancelled by mutual agreement. Funds were returned to the Buyer.',
    'completed_work': 'Completed Work?',
    'you_buyer_agree_cancel': 'You and Buyer Agree to Cancel',
    'both_sides_agree_drop_payment_returned_buyer': 'Both sides agree to drop the order. Payment is returned to the buyer\'s balance.',
    'force_cancel_order': 'Force Cancel Order',
    'close_order_refund_buyer_negative_effect': 'Close the order, refund the buyer (has a negative effect on your rating).',
    'buyer_not_submit_required_information_start_working': 'Buyer did not submit required information for me to start working',
    'buyer_not_responding_messages': 'Buyer is not responding to my messages',
    'some_buyers_take_their_time_until_they_reply': 'Some buyers take their time until they reply: Time difference, local holidays and personal constraints are common reasons for lack of response. If 3 days (or more) have passed and you still did not get a response, you can issue a Mutual Cancellation Request.',
    'how_do_complete_order_get_paid': 'How do I complete the order and get paid?',
    'have_submit_work_deliver_completed_tab': 'You have to submit your work using the Deliver Completed Work tab. Your buyer will then have 3 days to respond, after which the order will be marked as complete.',
    'order_complete': 'This order is complete.',
    'continue_talking_buyer_conversation_page': 'You can continue talking with the buyer in the conversation page.',
    'i_will': 'I will ',
    'for': 'for',

    /*shop*/
    'shop': 'Shop',
    'shop_status': 'Shop Status',
    'no_reviews': 'No Reviews',
    'edit_shop': 'Edit Shop',
    'edit_services': ' Edit Services',
    'order_delivered_thank_you': 'طلب تسليم ، شكرا لك!',
    'order_rejected_please_revise_deliver': 'تم رفض الطلب. يرجى مراجعة وتسليم مرة أخرى.',
    'work_rejected_buyer': 'آسف ، ولكن تم رفض عملك من قبل المشتري',

    /*edit shop*/
    'upload_cover_photo': 'Upload Cover Photo',

    /*my client request*/
    'running_job_client': 'My Running Job ( As Client )',
    'reference_id': 'Reference ID',
    'orders': 'Orders',
    'order_date': 'Order Date',
    'expiry_date': 'Expiry Date',
    'payment': 'Payment',
    'late_delivery': 'Late Delivery',
    'processing': 'processing',
    'cancelled': 'Cancelled',
    'completed': 'Completed',
    'delivered': 'Delivered',
    'closed': 'Closed',
    'track_request': 'Track Request',
    'note_funded_projects_display': 'Note: All funded projects will be display here.',

    /*Freelancer request*/
    'job_freelancer': 'My Running Job (As Freelancer)',

    /*Applied Job request*/
    'my_applied_job': 'My Applied Job',
    'bidding_date': 'BIDDING DATE',
    'bidding_amount': 'BIDDING AMOUNT',
    'estimated_time_complete_c': 'ESTIMATED TIME TO COMPLETE',
    'message_client': 'MESSAGE TO CLIENT',
    'award_status': 'AWARD STATUS',
    'client_fund_status': 'CLIENT FUND STATUS',

    /*All Jobs*/
    'all_jobs': 'All Jobs',
    'all': 'All',
    'skills': 'Skills',
    'price_range': 'Price range',
    'preferred_location': 'Preferred location',
    'featured': 'Featured',
    'image_c': 'IMAGE',
    'request': 'REQUEST',
    'bids_c': 'BIDS',
    'budget_c': 'BUDGET',
    'request_owner': 'REQUEST OWNER',
    'bid_now': 'BID NOW',
    'send_offer': 'Send an offer',
    'view_project': 'View Project',
    'awarded_you': 'Awarded to you',
    'awarded_other': 'Awarded to other',
    'radius_range': 'Radius',

    /*Job Details*/
    'job_details': 'Job Details',
    'budget': 'Budget :',
    'created_c': 'CREATED',
    'file_attachment': 'File Attachment',
    'offer_work_job_bid': 'Offer to work on this job now! Bid Now',
    'bid_job': 'Your bid for this job',
    'your_email_address': 'Your email address',
    'describe_your_proposal': 'Describe your proposal',
    'estimated_time_complete': 'Estimated time to complete',
    'freelancers_bidding_job': 'freelancers are bidding for this job',
    'estimate': 'Estimate',
    'awarded': 'Awarded',
    'apply_for_job': 'Apply for Job',
    'award': 'Award',
    'min_bid_price': 'Min Bid Price',
    'max_bid_price': 'Max Bid Price',
    'total_bids': ' Total Bids',

    /*services*/
    'select_services': 'Select Services',
    'currency': 'Currency',
    'price': 'Price',
    'prices': 'Prices',
    'time_hours': 'Time (Hours)',
    'reset': 'Reset',
    'add_services': 'Add Services',
    'time': 'Time',
    'edit': 'Edit',

    /*subservices*/
    'services_found': 'No services found!',

    /*allservices*/
    'all_services': 'All Services',

    /*Gallery Image*/
    'upload_gallery_image': 'Upload Gallery Image',
    'add_image': 'Add Image',
    'image': 'Image',
    'no_images_found': 'No images found!',

    /*Stripe Form*/
    'full_name_req': 'Full Name is required.',
    'email_req': 'Email Address is required.',

    /*wallet*/
    'minimum_withdraw_amt': 'Minimum Withdraw Amt',
    'shop_balance': 'Shop Balance',
    'withdraw_amount': 'Withdraw Amount',
    'withdraw_option': 'Withdraw Option',
    'enter_paypal_id': 'Enter Paypal ID',
    'card_id': 'Card ID',
    'enter_stripe_email_id': 'Enter Stripe Email ID',
    'enter_payumoney_email_id': 'Enter Payumoney Email ID',
    'bank_account_no': 'Bank Account No',
    'bank_name_address': 'Bank Name and Address',
    'ifsc_code': 'IFSC Code',
    'upcoming_payments': 'Upcoming Payments',
    'customer_name': 'Customer Name',
    'amount': 'Amount',
    'withdraw_mode': 'Withdraw Mode',
    'paypal_id': 'Paypal Id',
    'stripe_id': 'Stripe Id',
    'payumoney_id': 'Payumoney Id',
    'bank_info': 'Bank Info',
    'completed_withdrawal': ' Completed Withdrawal',
    'your_balance': 'Your balance is :',
    'my_released_payments': 'My Released Payments',
    'escrow_account': 'Escrow Account',
    'wallet_date': 'Date',
    'wallet_amount': 'Amount',
    'wallet_id': 'ID',
    'wallet_employee_name': 'Employee Name',
    'wallet_employer_name': 'Employer Name',
    'wallet_job_name': 'Job Name',
    'wallet_processing_fee': 'Processing Fee',
    'wallet_my_balance': 'My Balance',
    'wallet_continue': 'Continue',
    'wallet_no_upcoming': 'No Upcoming Payment Available',
    'wallet_no_pending': 'No Pending Payment Available',
    'wallet_no_com_with': 'No Completed Withdrawal Available',
    'wallet_no_pending_escrow': 'No Pending Escrow Payment Available',
    'wallet_no_com_escrowwallet_no_com_escrow': 'No Completed Escrow Payment Available',

    /*Feature Job*/
    'feature_job': 'Feature Job',
    'feature_request': 'Feature Request',
    'feature_request_para1': 'When you feature a request it will be shown before other requests on the website.',
    'feature_service': 'Feature Service',
    'feature_service_para1': 'When you feature a Service it will be shown before other Services on the website.',
    'pay_available_balance': 'Pay using available balance',
    'pay_using_paypal': 'Pay using PAYPAL',
    'pay_using_payumoney': 'Pay using PayuMoney',

    /*Feature success*/
    'payment_success_c': 'PAYMENT SUCCESS',
    'payment_successful': 'Your payment has been successfully accepted',
    'payment_id': 'Your Payment ID -',

    /*edit shop*/
    'shop_name': 'Shop Name',
    'shop_phone_no': 'Shop Phone No ',
    'shop_start_time': 'Shop Start Time',
    'shop_cover_photo': 'Shop Cover Photo',
    'select_image_size': '[Please select an image 1400px / 300px]',
    'advance_booking_upto': 'Advance Booking upto',
    'allowed_bookings_per_hour': 'Allowed Bookings Per Hour',
    'tax': 'Tax (%)',
    'shop_address': 'Shop Address',
    'shop_description': 'Shop Description',
    'shop_time': 'Shop End Time',
    'shop_profile_photo': 'Shop Profile Photo',
    'please_select_image_150px': '[Please select an image 150px / 150px]',
    'shop_registration_document': 'Shop registration document',
    'please_upload_pdf_image_only': '[Please upload pdf or image only]',

    /*new*/
    /*pay request*/
    'fund_now': 'Fund Now!',
    'fund_price': 'Fund price',
    'no_data_found': 'No Data Found!',
    'paynow': 'Pay Now',

    /*new*/
    /*booking info*/
    'booking_details': 'Booking Details',
    'selected_services': 'Selected Services',
    'service_charge': 'Service Charge',
    'total_charges_c': 'TOTAL CHARGES',
    'proceed_checkout_c': 'PROCEED TO CHECKOUT',

    /*new*/
    /*payment*/
    'payment_confirmation': 'PAYMENT CONFIRMATION',

    /*new*/
    /*404*/
    'page_not_found': '404 Page not found!',
    'requested_page_was_not_found': 'The requested page was not found',

    /*footer*/
    'pages': 'Pages',
    'about': 'About',
    'terms_conditions': 'Terms and Conditions',
    'privacy_policy': 'Privacy Policy',
    'blog': 'Blog',
    'contact': 'Contact',
    'customers': 'Customers',
    'how_works': 'How it works',
    'safety': 'Safety',
    'service_guide': 'Service Guide',
    'how_pages': 'How To Pages',
    'other_pages': ' Other Pages',
    'pros': 'Pros',
    'success_stories': 'Success stories',
    'questions': ' Questions?',
    'contact': 'Contact',
    'android': 'Android',
    'iphone': 'Iphone',
    'download_thumbsup_app': 'Download Thumbsup App',
    'all_rights_reserved': 'All Rights Reserved. Designed by',
    'disclaimer': 'Disclaimer',
    'cookie_policy': 'Cookie Policy',
    'acceptable_use_policy': 'Acceptable Use Policy',
    'dcma': 'DCMA',
    'refund_policy': 'Refund Policy',
    'cookies_privacy': 'Cookies & Privacy',
    'cookies_privacy_text': 'This website uses cookies to ensure you get the best experience on our website',

    /*verification*/
    'otp_text': 'Hello from Djobzy.com, Your OTP for verification is ',
    'password_to_access_your_settings': 'Password to access your settings',
    'by_linking_your_account': 'By linking your account, you agree to the Facebook',
    'fb_terms': 'Terms',
    'fb_data_policy': 'Data Policy',
    'fb_and': ' and',
    'fb_cookie_policy': 'Cookie Policy',
    'you_also_agree_to_our': 'You also agree to our',
    'you_also_agree_to_our_google': 'You agree to our',
    'terms_conditions_and_cookie_policy': 'Terms & Conditions and Cookie Policy',
    'you_may_receive_sms_notifications': 'You may receive SMS notifications from us or Facebook and can opt-out at any time',
    'you_may_receive_sms_notifications_google': 'You may receive SMS notifications from us or Google and can opt-out at any time',
    'step_verification_completed': '2nd Step Verification Completed',
    'you_are_verified_to': 'You are now Verified to',
    'now_you_can_use_the_functionalities_of_djobzy': 'Now you can use the full functionalities of Djobzy',
    'congratulations': 'Congratulations!',
    'badge_will_be_added_soon_to_your': 'A badge will be added soon to your profile, indicating your new status. With this level, you are among the privileged members of the Djobzy community, and we are excited to have this journey with you.',
    'your_verification_level': 'Your Verification Level',
    'higher_verification_levels_increases': 'Higher Verification levels increase your chances of landing a job or finding employees, Showing you higher in search results, Enabling you to gain others trust easier, and enhancing your Djobzy Experience.',
    'thank_you_for_requesting_an_interview': 'Thank you for requesting an interview.',
    'choose_country': 'Choose Country',

    /*settings*/
    'setting_confirm_password': 'Confirm Password',
    'setting_password': 'Password',
    'setting_confirm': 'Confirm',
    'close_your_account': 'Close your account',
    'delete_your_djobzy_account': 'Delete your Djobzy account',
    'delete_the_account': 'Delete the account',
    'delete_your_account_means': 'Delete your account means',
    'you_will_loose': 'You will loose all the data and content in your account, like your competencies, descriptions, service packs, messages and all files uploaded to your account pages',
    'you_wont_be_able': 'You won\'t be able to apply for a job or to post job without an account',
    'if_your_account_has_been_hacked': 'If your account has been hacked',
    'if_that_is_the_reason_why_you': 'If that is the reason why you are willing to delete please contact us and we\'ll help you to get your unique access back',
    'will_it_be_possible_to_recover': 'Will it be possible to recover your account in future?',
    'no_deleteing_your_account_means': 'No, deleteing your account means that you won\'t be able to access to it in future. Also your username will become available again',
    'have_you_withdrawn_your_funds_yet': 'Have you withdrawn your funds yet?',
    'before_you_have_your_account_deleted': 'Before you have your account deleted, please make sure you have withdrawn your money from your account, retriving fund from a deleted account will be not possible',
    'delete_email': 'Email',
    'delete_password': 'Password',
    'get_a_code': 'Get a code',
    'put_code': 'Put code',
    'enter_pin': 'Enter PIN',
    'default_profile_text': 'Your default profile is the one that you use more often. When you open Djobzy your default profile will launch first.',
    'postal_code': 'Postal Code',
    'contact_info': 'Contact Info',

    /*job ppst*/
    'choose_template': 'Choose Template',
    'job_post_cancel': 'Cancel the Job Post',

    /*Category*/
    'category_title': 'Categories',
    'category_search': 'Search for a Category',

    /*category controller*/
    'cant_find_your_category': 'Can\'t find your category?',
    'request_a_new_category': 'Request a new category',

    /*wallet*/
    'provide_withdraw_amount': 'Please provide withdrawal amount',
    'choose_withdraw_mode': 'Please choose a withdrawal mode',
    'provide_paypal_id': 'Please provide PayPal Id',
    'provide_stripe_id': 'Please provide Stripe Id',

    /*private chat*/
    'search_for_users': 'Search for people...',
    'please_choose_a_user': 'Start conversation',
    'keep_in_touch_chat': 'Keep in touch',
    'all_files': 'All Files',
    'block': 'Block',
    'unblock': 'Unblock',
    'are_you_sure_to_block': 'Are you sure you want to block',
    'are_you_sure_to_unblock': 'Are you sure you want to unblock',

    /*Create job*/
    'add_level': 'Add level',
    'press_choose_multiple_files': 'To add multiple files, click on “Add Attachment”, hold the Shift button and choose files.',
    'the_maximum_file_size': 'The maximum file size is',
    'the_accepted_formats_are': 'The accepted formats are jpg, jpeg, doc, docx, pdf, png.',
    'publish': 'Publish',
    'review_and_edit': 'Review and Edit',
    'cancel_edit': 'Cancel',

    /*register page*/
    'register_success': 'Registered Successfully',
    'thank_you_for_signing_up': 'Thank you for Signing Up',
    'please_check_your_email_activate': 'Please check your email to Activate your account',

    /*verification step*/
    'upload_document_to_verify_address': 'Upload document to verify address',

    /*forgot*/
    'we_have_sent_you_an_email': 'We have sent you an Email with a link to reset your password',
    'email_including_spam_box': 'Please check your Email including spam box',

    /*job details*/
    'are_you_sure_to_hire': 'Are you sure you would like to hire',

    /*profile*/
    'create_from_template': 'Create from Template',
    'choose_a_template': 'Choose a Template',
    'create_a_new_service_pack': 'Create a New',
    'you_can_either_create_a_brand_new': 'You can either create a brand new job request or use your previous one as a template.',
    'save_publish': 'Save and Publish',
    'category_you_trying_to_delete': 'The category you are trying to delete belongs to a job or job request',
    'delete_the_service_pack_first': 'Please delete the job or job request first to be able to delete the category',
    'add_a_service_pack': 'Add a job request',
    'add_fixed_rate': 'Add total price',

    /*Payment page*/
    'i_hereby_agree_to_abide': 'I hereby agree to abide by the',
    'policies_i_will_release': 'and Policies of Djobzy.com. I will release the payment upon successful completion of service(s) to the Employee',
    'i_hereby_agree_to_abide1': 'I hereby agree to abide by the',
    'and_policies_of_djobzy': 'and Policies of Djobzy.com.',

    /*Tooltip*/
    'tooltip_provided_services': 'Promoting Services is Free. Any of your expertise or talent can be promoted here. You can combine different services into one like fiixing and cleaning furniture. Create as many services as you wish here and increase your chances of landing a job.',
    'tooltip_involved_category': 'Use this section if you only want to be involved in a single category, here you can write about yourself, your personal expertise, and can upload files to prove your great service level.',
    'tooltip_suggested_jobs': 'Based on your activities, we think you might be interested in the jobs in these categories.',
    'tooltip_setting_prices': 'Write approximate hourly prices and total amount that you want to offer for the job and we will calculate hours based on those inputs, Also you can add ranges to prices, if you are not sure. And you can change your bid later as well.',
    'tooltip_servicepack_prices': 'Employers will see the price with the 15% service fee included.',
    'tooltip_counter_offer': 'You can create a new offer with changed hourly or Total prices. Active Hours for the job will be Automatically recalculated based on those inputs.',
    'tooltip_bidding_profiles': 'These are the employees that applied for this job with their price offers.',
    'tooltip_payment_methods': 'You’ll need to add a billing method to your account to pay an employee or boost your posts.',
    'tooltip_banking_information': 'Add your banking information to withdraw money to your bank account from Djobzy.',

    /*Profile page*/
    'current_work': 'Current Work',
    'current_contract': 'Current Contracts',
    'work_history_and_reviews': 'Work History And Reviews',
    'contract_history_and_reviews': 'Contract History And Reviews',

    /*Landing page*/
    'slider_text_1': 'At Djozby we are doing our best to make the processes of employment as fast and effective as possible. We aim to help our users save time and money by directly connecting them to the Service Provider / User.',
    'slider_text_2': 'Whether you are self-employed, unemployed, full-time employed, a student or retired — you can make extra income on Djobzy or employ others on competitive pricing to save your time and money.',
    'slider_text_3': 'Need help preparing for a party? Hire someone to help set up the chairs, prepare the food, or maybe you need a DJ or bartender?',
    'slider_text_4': 'Are you moving and need someone to help pack, clean, and take unwanted items to the thrift store and recycle depot?',
    'slider_text_5': 'Is your work schedule too hectic for you to even take your dry cleaning in? Maybe, you need someone to take your car in to be serviced? The right person is just a click away.',
    'slider_text_6': 'You’ll be surprised how many people would apply & bid on your task. No Task or Errand is too great or small. There is always someone willing to lend you a hand.',
    'slider_text_7': 'Someone in another city buying & delivering a birthday gift for your mom to her surprise.',
    'slider_text_8': 'You need a person to do market research for your company in Africa.',
    'slider_text_9': 'Imagine you could ask others in any part of the world to perform a task for you, imagine the world without borders.',
    'slider_text_10': 'With Djobzy that is a possibility now. Here you can hire for both physical & virtual jobs on a global scale.',
    'slider_text_11': 'Post your job on Djobzy and lots of qualified employees will apply.',
    'slider_text_12': 'You can check Djobzy’s live profile of the applicants including reviews and verification levels.',
    'slider_text_13': 'Instead of guessing from the applicant’s resumes you can test the actual performance of the candidates by hiring them through Djobzy for a real task for a couple of hours.',
    'slider_text_14': 'The employees are incentivized to appear for the interview, show their best potentials and also get paid for a couple of hours.',
    'slider_text_15': 'Hiring through Djobzy would lift the extra burden of employment process off your legal team’s shoulders.',
    'slider_text_16': 'This would Boost your HR department, would help you to employ qualified employees rather than the employees only with a nice resume, and increase your company’s productivity.',
    'slider_text_17': 'Gain immediate trust from employers wherever you go.',
    'slider_text_18': 'Djobzy profile moves with you.',
    'slider_text_19': 'In case you are relocating to another city / country you do not need to start from zero again.',
    'slider_text_20': 'Simply change your profile address and based on your previous references you can start providing your services immediately.',
    'slider_text_21': 'We are using 7 levels of verification. The higher verification level you have, the easier people can trust you.',
    'slider_text_22': 'We use escrow account to keep your funds safe',
    'slider_text_23': 'Employers and employees can review each other after job completion ',
    'slider_text_24': 'In real life we are employees and employers at the same time, when you get a coffee from a cafe you employ the staff for a couple of seconds and 2 hours later you are providing another service to someone else.',
    'slider_text_25': 'Djobzy is trying to harness the technology in our favour to offer a helping hand to one another resulting in stimulating human connections, saving money and earning additional income.',
    'slider_text_26': 'Think of how many talents, competencies or simple skills you have. There is always someone around who can appreciate your help. Register to start improving the social environment around you and expanding the scope of your activities.',
    'slider_text_27': 'You can create any jobs / tasks / errands in your mind, mention your budget and choose the categories involved and you will find employees bidding on your job.',
    'slider_text_28': 'You can also look for the jobs / tasks / errands anywhere on the map and start bidding for those jobs.',
    'slider_text_29': 'Work on your own schedule',
    'slider_text_30': 'No long-term commitment',
    'btn_register_now': 'Register Now',
    'it_only_takes_seconds': 'It only takes 15 seconds',
    'it_takes_minutes_to_post_a_job': 'It takes 2 minutes to Post a Job',
    'short_term_jobs': 'Short-Term Jobs',
    'post_any_tasks_errands': 'Post any Tasks / Errands',
    'hire_an_employee_in_another_city_country': 'Hire an Employee in another City / Country',
    'imagine_text': 'IMAGINE!!!',
    'djobzy_for_companies': 'Djobzy for Companies',
    'career_passport': 'Career Passport',
    'verified_users_fair_system': 'Verified Users / Fair System',
    'same_time_employer_employee': 'Same Time Employer / Employee',
    'get_employed_based_on_any_of_your_expertise': 'Get Employed Based on any of your Expertise',
    'job_landing': 'Job',
    'employee_landing': 'Employee',
    'search_on_the_map': 'search on the Map',

    /*404 page*/
    'oops_so_sorry_it_seems': 'Oops...so sorry, it seems',
    'the_page_requested_was_not_found': 'The page requested was not found',
    'lets': 'Let’s',
    'back_home': 'Back home',
    'for_now': 'for now',

    /*Blog*/
    'blog_categories': 'Blog Categories',
    'forum': 'Forum',
    'explore_the_blog': 'Explore the blog',
    'go_to_the_forum': 'Djobzy Forum',
    'search_for_an_article': 'Search for an article',
    'write_your_thought': 'Write your thought',
    'discuss_the_article': 'Discuss the article',

    /*Knowledge*/
    'knowledge_categories': 'Knowledge Categories',
    'forum': 'Forum',
    'explore_the_knowledge': 'Explore the Knowledge',
    'go_to_the_forum': 'Djobzy Forum',
    'search_for_an_article': 'Search for an article',
    'write_your_thought': 'Write your thought',
    'discuss_the_article': 'Discuss the article',

    /*Edit profile*/
    'add_experience': 'Add Experience',

    /*About us*/
    'hello': 'Hello!',
    'about_text_1': 'Meet our amazing team. We live on different sides of the world but that makes us only stronger. We are open to new ideas and always monitor how the world is changing due to global trends. We are willing to create good trends ourselves and to make the most efficient service ever, so keep an eye on us.',
    'about_text_2': 'Djobzy stimulates human values by showing up and offering a helping hand to one another and overcoming daily tasks that others may need to help them with one stride at a time without any long term commitment, Djobzy brings the best of us out.',
    'about_text_3': 'Djobzy is the best use of technology in innovative ways to help us improve our societies and come together as humans who care and want to build a better collaborative future for ourselves and our children.',
    'mission': 'Mission',
    'vision': 'Vision',
    'follow_us': 'Follow us',
    'create_job_h': 'h',
    'create_job_hour': 'Hour',
    'create_job_hours': 'Hours',

    /*profile*/
    'title_for_service_pack': 'Title for job request',
    'description_for_service_pack': 'Description for job request',
    'describe_your_proposal_to_employers': 'Give details. How do you provide your service? How long does it take? Try keeping it simple yet sufficient.',

    'paypal': 'PayPal',
    'stripe': 'Credit/Debit Card',
    'bank_transfers': 'Bank Transfer',
    'deactivated_jobs': 'Deactivated Jobs',
    'my_deactivated_jobs': 'My Deactivated Jobs',
    'no_deactivated_jobs': 'No Deactivated Jobs',
    'deactivated_archieve': 'Deactivate & Archive this job',
    'deactivated': 'Deactivated',
    'reactivate': 'Reactivate',
    'are_you_sure_to_archieve': 'Are you sure you want to deactivate this job post?',
    'are_you_sure_to_reactivate': 'Are you sure you want to reactivate this job post?',

    'find_out_more_about': 'Find out more about',
    'watch_video': 'Watch Video',
    'landing_find': 'Find',
    'landing_the': 'the',
    'landing_best': 'Best',
    'the_ultimate_hiring_platform': 'The Ultimate Hiring Platform',
    'hire_and_get_hired_for_any_task_in_any_job_ategory': 'Hire and Get Hired for any Task in any Job Category',

    /*Referral*/
    'referrals_username': 'Referral\'s username',
    'referral_wallet': 'Referral Wallet',
    'my_referral_wallet': 'Referral Wallet',
    'my_referrals_wallet': 'Referral Wallet',
    'my_referrals_history': 'My Referral History',
    'date_of_joining': 'Date Of Joining',
    'user': 'User',
    'my_passive_income': 'My Passive Income',
    'id': 'ID',
    'you_can_collect_the_income': 'You can collect the income once a month',
    'collect_the_payments': 'Collect the Payments',
    'do_you_want_to_collect': 'Are you sure you want to collect the payments?',
    'as_you_are_referred': 'You Saved over ',
    'discount': ' of fees, Due to your referral status',
    'referral_discount': 'Referral Discount',
    'you_have_received_referral_income_from': 'You have received Referral income from',
    'referral': 'Referral',

    'you_are_fully_verified': 'You are Fully Verified',
    'a_badge_will_be_added_soon': 'A badge will be added soon to your profile indicating your new status. With this level, you are among the privileged member of Djobzy community and we are excited to have this journey with you.',

    'seen': 'Seen',
    'unseen': 'UnSeen',
    'newest': 'Newest',
    'oldest': 'Oldest',
    'new_notifications': 'New Notifications',
    'old_notifications': 'Old Notifications',
    'from': 'From',
    'notification': 'Notification',
    'notification_date': 'Date',

    'payment_type': 'Payment Type',
    'to_unsubscribe_please_type': 'To unsubscribe, please type your email here:',

    'successfully_collected_amount': 'You have successfully collected the payments',
    'email_already_exist_so_please_try': 'Email already exist, so please try with another account',
    'by_signing_up_you_agree_to_our': 'By signing up you agree to our',
    'register_terms': 'terms',
    'of_service': 'of service',
    'original_job_amount': 'Original Job Amount',
    'amount_credited': 'Amount Credited',
    'use_as_a_referral': 'Use as a referral',
    'the_jobs_are_sorted_based_on_hourly': 'The jobs are sorted based on hourly and fixed rates. It is required to set both parameters',
    'you_can_always_chat_with_the_other': 'You can always chat with the other party to agree on a total price for a project',
    'you_can_promote_your_job_with_a_small_payment': 'You can boost your job with a small payment',
    'bring_your_post_to_the_top': 'Bring your post to the top of the page by boosting it. The more you spend the more possibilities we have to advertise your job and bring more attention to your post.',
    'the_promotion_would_last_for_week': 'The promotion would last for 1 week.',
    'promote_this_job': 'Boost this Job',
    'continue_without_promoting': 'Continue without boosting',
    '2_steps_to_start': '2 STEPS TO START',
    'to_fully_acitvate_your_account': 'Please complete at least two verification steps to start using the website.',
    'select_level': 'Select Level',
    'mid_level': 'Mid. Level',
    'fluent': 'Fluent',
    'refer_and_earn': 'Refer and Earn',
    'invite_your_friends': 'Invite your friends and get bonuses',
    'invite_with_email': 'Invite with an email',
    'invite_with_link': 'Invite with a link',
    'or_share_with_social_media': 'Or share with social media',
    'about_our_referral_system': 'About our referral system',
    'successfully_invited': 'Successfully invited',
    'please_put_a_valid_email': 'Please put a valid email',
    'online_jobs': 'jobs ',
    'online_employees': 'employees ',
    'in': 'in ',
    'at': 'at ',
    'near_me': 'near me',
    'suggested_categories': 'Suggested categories: ',
    'improve_your_profile_here': 'Improve your profile here. The more details you put is the more chances to be hired.',
    'start_selling_your_services': 'Start selling your services.',
    'main_features_of_your_account': 'Main features of your account.',
    'here_you_can_combine_different': 'Here you can combine different categories to create your own unique job request to get hired for this particular combination of services.',
    'improve_your_profile_here_details': 'Improve your profile here. The more details you put is the more chances to find a good employee faster.',
    'start_posting_any_job_or_task': 'Start posting any job or task.',
    'profile_title': 'Profile Title',
    'date_of_income': 'Date of Income',
    'joined_with_referal': 'New user joined with your referral link',
    'action': 'Action',
    'you_received_passive_income_for': 'You received passive income for',
    'joined_with_your_invitation': 'Joined with your invitation',
    'fast_and_effective_employment_process': 'Fast and effective employment process',
    'saving_time_and_money_by_directly': 'Saving time and money by directly connecting to the service provider.',
    'are_you_moving_and_need_someone_to_help': 'Are you moving and need someone to help?',
    'there_is_always_someone_willing_to': 'There is always someone willing to lend you a hand.',
    'imagine_the_world_without_borders': 'Imagine the world without borders.',
    'with_djobzy_it_is_a_possibility_now': 'With Djobzy it is a possibility now.',
    'here_you_can_hire_for_both_physical': 'Here you can hire for both physical & virtual jobs on a global scale.',
    'gain_immediate_trust_of_employers': 'Gain immediate trust of employers wherever you go.',
    'web_shop_of_services': 'Web Shop of Services',
    'all_services_you_need_under_one_umbrella': 'All services you need under one umbrella.',
    'anyone_can_make_money_instantly': 'Anyone can make money instantly',
    'whether_you_are_a_student_retired': 'Whether you are a student, retired, employed or unemployed you can always make money on your own schedule.',
    'be_your_own_boss': 'Be your own boss',
    'work_on_freelance_on_your_own_terms': 'Work as a freelancer on your own terms',
    'we_have_a_7_level_verification_system_to': 'We have a 7 level verification system to make your connections more trustworthy.',
    'we_use_an_escrow_account_to_keep_your': 'We use an escrow account to keep your funds safe.',
    'we_have_a_fair_review_system_so_you': 'We have a fair review system, so you could use others\' experiences to your benefit.',
    'employer_mployee_at_the_same': 'Employer & Employee at the same time',
    'when_you_register_you_get_accounts': 'When you register you get 2 accounts',
    'going_from_employee_to_employer': 'Going from employee to employer is very easy',
    'be_an_entrepreneur_while_you_work': 'Be an entrepreneur while you work',
    'there_is_always_someone_who_needs': 'There is always someone who needs exactly what you do',
    'list_all_of_your_areas_of_expertise': 'List all of your areas of expertise',
    'use_your_skills_and_talents_to_earn': 'Use your skills and talents to earn money',
    'job_employee_search_on_the_map': 'Job / Employee search on the Map',
    'look_for_the_jobs_tasks_errands': 'Look for the jobs / tasks / errands anywhere on the map',
    'use_tools_to_find_jobs_near_you': 'Use tools to find jobs near you',
    'earn_while_travelling': 'Earn while travelling',
    'you_can_promote_category_small_payment': 'You can boost Your Category with a small payment',
    'minimum_withdraw_amount_is': 'Minimum withdrawable amount is ',
    'maximum_withdraw_amount_is': 'and maximum withdraw amount is ',
    'get_ready_to_find_services_online': 'Jobs ',
    'get_ready_to_find_employees_online': 'Employee ',
    'djobzy_is_an_online_your_own_schedule': 'Djobzy is an online platform where you can employ and get employed on your own schedule',
    'tell_us_your_story': 'Tell us your story',
    'service_pack': 'Job Requests',
    'we_recomend_you_to_keep_verifying': 'We recomend you to keep verifying to increase your exposure and level of trust on your profile',
    'remember': 'Remember!',
    'the_verification_levels_equals': 'the verification levels equals more opportunities.',
    'start_using_the_website': 'Start using the Website',
    'continue_verification': 'Continue Verification',
    'level': 'Level',
    'see_more': 'See more',
    'see_less': 'See less',
    'optional': 'Optional',
    'request_a_withdraw_here_put_amount': 'Request a withdraw here. Put the amount you wish to withdraw, choose an account you want to receive money to and click "Continue" to complete the process.',
    'here_you_can_see_all_payment_activities': 'Here you can see all the payment activities related to your contracts.',
    'click_add_information_about_yourself': 'Click here to add information about yourself. Use this button in the future for updating the page.',
    'add_categories_you_wish': 'Add categories you wish to be involved in. This helps your future employees to find you.',
    'add_categories_you_wish1': 'Add categories you wish to be involved in. This helps your future employers to find you.',
    'if_you_want_add_additional_information': 'If you want to add any additional information about yourself or the services you provide use this section.',
    'explore_the_blog': 'Explore the blog',
    'choose_the_categories': 'Choose the Categories',
    'change_profile_photo': 'Change Profile Photo',
    'has_been_transfered': 'has been transferred',
    'to_your': 'to your',
    'if_you_cannot_find_the_email': 'If you can not find the email in your inbox, please',
    'check_your_spam': 'check your spam.',
    'hide_this_section': 'Hide this from other users',
    'show_this_section': 'Show this to other users',
    'my_active_contracts': 'My Active Contracts',
    'my_current_jobs': 'My Current Jobs',
    'completed_contracts': 'Completed Contracts',
    'my_completed_contracts': 'My Completed Contracts',
    'my_completed_jobs': 'My Completed Jobs',
    'my_closed_jobs': 'My Closed Jobs',
    'djobzy_chat_messages': 'Djobzy Chat Messages',
    'notification_sound': 'Notification Sound',
    'email_notifications': 'Email Notifications',
    'we_strongly_recommend_keep_notifications': 'We strongly recommend you to keep this notifications enabled in order to be informed about any offers, activities and incoming payments.',
    'are_you_sure_to_disconect': 'Are you sure you want to disconnect your social media account?',
    'report_employee': 'Report employee',
    'introduction_letter_required': 'Introduction Letter (Required)',

    /*employee employer profile tooltip */
    'employer_profile_title_tooltip': 'Please summarize in one short sentence your current main focus or industries that you are employing in. This text will be displayed in the search results, and that’s how people will find you.',
    'employee_profile_title_tooltip': "Please summarize in one short sentence the main feature of your profile. For example, I'm a gardener with 15 years of experience. If you provide many services, then prioritize some.  You can change the title at any time.",
    'employee_about_me_tooltip': 'Please describe your talents, expertise, hobbies, or anything else worth mentioning to get noticed by a potential employer.',
    'employer_about_me_tooltip': 'Please describe the qualities you expect from an employee: honesty, agility, professionalism and availability. Also, you can tell what makes you a good employer (precise goal setting, politeness)',
    'tooltip_attachment': 'Attach your portfolio, license, certificate or other documents to showcase your accomplishments.',
    'tooltip_asset': 'Here you can indicate any tool or program that is required for work (camera, Tablet…)',
    'tooltip_Vehicle': 'Add vehicle type if you are involved in transport related jobs',
    'tooltip_licenses': 'Add licenses if you are involved in specific industries',
    'tooltip_certificate': 'Add certifications  to emphasize your most valuable skills',
    'employee_service_calendar_guide': "This calendar shows your working hours available for booking by employers. When you create a promoted service, it is automatically open for booking at any available time.If your service price is non- negotiable, then someone can book that service without your confirmation.If the price is negotiable, you will have to approve each time the booking request. This calendar can be enabled or disabled at any time, but all the services that has been booked should be provided.",
    'non_negotiable_service_guide': "This option means that the client can book your service without your confirmation and you must provide it at that date and time. This option is best suited for those who have a high flow of clients and short - term services, like beauty salon or consultancy.",
    'calendar_break_hours': 'You can specify when you are off duty during the working day. These hours will be unavailable for booking',
    /*wallet & referral wallet*/
    'my_balance': 'My Balance shows how much money you have in your wallet',
    'referral_wallet_social_media': 'Your referral link will be shared with your friends via your social media account.',
    'blog_forum': 'Djobzy Forum is a great place to share feedback.  Here you can ask and answer questions, search topics and learn more.',
    'tooltip_referral_wallet': 'Commission earned through user invitations via the Djobzy referral program.',
    /**************/
    'my_offer_price': 'Make an offer to an employer by adding your desired total price and hourly rate for the job',
    'tooltip_hidejob': 'Hide the job post if it is not interesting. It will help us to improve your suggestions.',
    'tooltip_likejob': 'Add the job post in favorites if you want to see more like this.',
    'tooltp_username': 'Your username will appear in the address of your profile. For example www.djobzy.com/name. Pick up any available username.',
    /***************/
    'tooltip_hidemoney': 'Amount is hidden',
    'earned': 'Earned',

    /******/
    'naive': 'Native or bilingual',

    'promoted': 'Boosted',//'Promoted',
    /******/
    'active_biddings': 'Active Bids',
    'expired_biddings': 'Expired Bids',
    'sent_proposals': 'My Bids',
    'bids': 'Bids:',
    'my_job_posts': 'My Job Posts',
    'no_completed_contract': 'You don’t have any completed contract',
    'no_completed_job': 'You don’t have any completed job yet',
    'no_received_application': 'You haven’t received any application yet',
    'no_active_contract': 'You don’t have any active contract',
    'received_applications': 'Received applications',


    'previous_bid': 'Previous bid',

    'didnt_receive_email': 'Didn’t receive an email?',
    'file_upload_limit_exhausted': 'You have exhausted the file upload limit, Please increase upload limit or delete the old attachments',
    'please_rate_and_review': 'Please rate and review ',
    'for': ' for ',
    'job': 'job',
    'hotel_booking': 'My Bookings',
};